### ISSUE TITLE
Category API Development

### ISSUE THREAD

**Issue by kimdg1105** [Bletcher-Project/bletcher-back#18]
### GET
-category 조회 관련
 - [x] GET /api/categories : 전체 카테고리 계층별로 가져오기
 - [x] GET /api/categories/?categoryid= : 해당 카테고리~한단계 밑 상속된 카테고리들 가져오기
 - [x] GET /api/categories/?categoryid= : 해당 카테고리를 포함한 모든 상속된 카테고리 가져오기

-post 조회 관련
 - [x] GET /api/posts/category/:id : 해당 카테고리의 모든 게시글 가져오기
 - [x] GET /api/posts/category/:nodeid= : 해당 카테고리~최하위 카테고리까지의 모든 게시글 가져오기

----
  api보다 계층화(셀프 조인)에 대해 디비 쪽을 많이 다룰 것 같습니다. 개발 중간중간 필요한 api가 있으면 리스트에 추가하겠습니다! 

## TODO-list
 - [x] 카테고리 모델 관계 재정의
 - [x] parent_id에 따른 노드 계층화
